global:
  secretStore:
    backend: vault
    name: vault-backend
    kind: ClusterSecretStore

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

bucketSecrets:
  - pipeline-bucket
  - user-bucket

s3:
  default_endpoint: http://s3.openshift-storage.svc
  default_region: none

awsPipelinesSecret:
  key: secret/data/hub/aws-connection-pipelines

clusterdomainurl: cluster.example.com
