{{- range $i := .Values.bucketSecrets }}
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-secret-s3-{{ $i }}
  namespace: ml-development
spec:
  data:
    - conversionStrategy: None
      match:
        remoteRef:
          remoteKey: pushsecrets/{{ $i }}
          property: AWS_ACCESS_KEY_ID
        secretKey: AWS_ACCESS_KEY_ID
    - conversionStrategy: None
      match:
        remoteRef:
          remoteKey: pushsecrets/{{ $i }}
          property: AWS_SECRET_ACCESS_KEY
        secretKey: AWS_SECRET_ACCESS_KEY
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: vault-backend
  selector:
    secret:
      name: {{ $i }}
  updatePolicy: Replace
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: s3-{{ $i }}
  namespace: ml-development
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: aws-connection-{{ $i }}
    template:
      type: Opaque
      engineVersion: v2
      data:
        AWS_SECRET_ACCESS_KEY: "{{ `{{ .aws_secret_access_key }}` }}"
        AWS_ACCESS_KEY_ID: "{{ `{{ .aws_access_key_id }}` }}"
        AWS_S3_BUCKET: {{ $i }}
        AWS_S3_ENDPOINT: {{ $.Values.s3.default_endpoint }}
        AWS_DEFAULT_REGION: {{ $.Values.s3.default_region }}
  data:
  - secretKey: aws_secret_access_key
    remoteRef:
      key: "pushsecrets/{{ $i }}"
      property: "AWS_SECRET_ACCESS_KEY"

  - secretKey: aws_access_key_id
    remoteRef:
      key: "pushsecrets/{{ $i }}"
      property: "AWS_ACCESS_KEY_ID"
{{- end }}
